### ISSUE TITLE
Add course_id as an optional parameter when creating an exam

### ISSUE THREAD

**Issue by dgcnz** [pmariniutec/easyexam-backend#18]
At this point in time, such action is implemented with the following endpoints:

1. `/api/exam/create`: Create an exam
2.  `/api/course/exam/add`: Add an existing exam to an existing course

It might be helpful if the payload sent to `api/exam/create` were to include course_id as an optional parameter so that the second step is omitted and the exam is immediately added to the course in step 1.

**Comment by mlovatonv** [comment]
#21
